//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEO_FPM_V3._0_Standard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEO_FPM_V3._0_Standard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about_3 {
            get {
                object obj = ResourceManager.GetObject("about-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap about_4 {
            get {
                object obj = ResourceManager.GetObject("about-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap About_US__5 {
            get {
                object obj = ResourceManager.GetObject("About US -5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bb1 {
            get {
                object obj = ResourceManager.GetObject("bb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bb11 {
            get {
                object obj = ResourceManager.GetObject("bb11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_1 {
            get {
                object obj = ResourceManager.GetObject("button-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_11 {
            get {
                object obj = ResourceManager.GetObject("button-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_2 {
            get {
                object obj = ResourceManager.GetObject("button-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_3 {
            get {
                object obj = ResourceManager.GetObject("button-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CEO_LOGO {
            get {
                object obj = ResourceManager.GetObject("CEO-LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CEO_LOGO1 {
            get {
                object obj = ResourceManager.GetObject("CEO-LOGO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_1 {
            get {
                object obj = ResourceManager.GetObject("F-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_11 {
            get {
                object obj = ResourceManager.GetObject("F-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_2 {
            get {
                object obj = ResourceManager.GetObject("F-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_21 {
            get {
                object obj = ResourceManager.GetObject("F-21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_3 {
            get {
                object obj = ResourceManager.GetObject("F-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_31 {
            get {
                object obj = ResourceManager.GetObject("F-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_4 {
            get {
                object obj = ResourceManager.GetObject("F-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_41 {
            get {
                object obj = ResourceManager.GetObject("F-41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_5 {
            get {
                object obj = ResourceManager.GetObject("F-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_51 {
            get {
                object obj = ResourceManager.GetObject("F-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_6 {
            get {
                object obj = ResourceManager.GetObject("F-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_61 {
            get {
                object obj = ResourceManager.GetObject("F-61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_62 {
            get {
                object obj = ResourceManager.GetObject("F-62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_63 {
            get {
                object obj = ResourceManager.GetObject("F-63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_64 {
            get {
                object obj = ResourceManager.GetObject("F-64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_65 {
            get {
                object obj = ResourceManager.GetObject("F-65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_7 {
            get {
                object obj = ResourceManager.GetObject("F-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_71 {
            get {
                object obj = ResourceManager.GetObject("F-71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_72 {
            get {
                object obj = ResourceManager.GetObject("F-72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_8 {
            get {
                object obj = ResourceManager.GetObject("F-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_81 {
            get {
                object obj = ResourceManager.GetObject("F-81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_9 {
            get {
                object obj = ResourceManager.GetObject("F-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap F_91 {
            get {
                object obj = ResourceManager.GetObject("F-91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Line1 {
            get {
                object obj = ResourceManager.GetObject("Line1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Line2 {
            get {
                object obj = ResourceManager.GetObject("Line2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_01 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_011 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_02 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_03 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_031 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_04 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_041 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_1 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGIN_11 {
            get {
                object obj = ResourceManager.GetObject("LOGIN-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_BG_01 {
            get {
                object obj = ResourceManager.GetObject("main-BG-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_BG_011 {
            get {
                object obj = ResourceManager.GetObject("main-BG-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_BG_02 {
            get {
                object obj = ResourceManager.GetObject("main-BG-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_BG_03 {
            get {
                object obj = ResourceManager.GetObject("main-BG-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_BG_031 {
            get {
                object obj = ResourceManager.GetObject("main-BG-031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_r2_c2 {
            get {
                object obj = ResourceManager.GetObject("main_r2_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_r2_c7 {
            get {
                object obj = ResourceManager.GetObject("main_r2_c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_r2_c9 {
            get {
                object obj = ResourceManager.GetObject("main_r2_c9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_r4_c1 {
            get {
                object obj = ResourceManager.GetObject("main_r4_c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu1_a {
            get {
                object obj = ResourceManager.GetObject("menu1-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu1_a1 {
            get {
                object obj = ResourceManager.GetObject("menu1-a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu1_a2 {
            get {
                object obj = ResourceManager.GetObject("menu1-a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu1_a3 {
            get {
                object obj = ResourceManager.GetObject("menu1-a3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu1_b {
            get {
                object obj = ResourceManager.GetObject("menu1-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu2_a {
            get {
                object obj = ResourceManager.GetObject("menu2-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu2_a1 {
            get {
                object obj = ResourceManager.GetObject("menu2-a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu2_b {
            get {
                object obj = ResourceManager.GetObject("menu2-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu3_a {
            get {
                object obj = ResourceManager.GetObject("menu3-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu3_a1 {
            get {
                object obj = ResourceManager.GetObject("menu3-a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu3b {
            get {
                object obj = ResourceManager.GetObject("menu3b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu4_a {
            get {
                object obj = ResourceManager.GetObject("menu4-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu4_a1 {
            get {
                object obj = ResourceManager.GetObject("menu4-a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu4_b {
            get {
                object obj = ResourceManager.GetObject("menu4-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New_Logo {
            get {
                object obj = ResourceManager.GetObject("New-Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Register_Activate_OK {
            get {
                object obj = ResourceManager.GetObject("Register-Activate-OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Register_Activate_OK1 {
            get {
                object obj = ResourceManager.GetObject("Register-Activate-OK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_3 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Screenshot_4 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Standard {
            get {
                object obj = ResourceManager.GetObject("Standard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status1 {
            get {
                object obj = ResourceManager.GetObject("status1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status2 {
            get {
                object obj = ResourceManager.GetObject("status2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text1 {
            get {
                object obj = ResourceManager.GetObject("text1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text2 {
            get {
                object obj = ResourceManager.GetObject("text2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text3 {
            get {
                object obj = ResourceManager.GetObject("text3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text4 {
            get {
                object obj = ResourceManager.GetObject("text4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text5 {
            get {
                object obj = ResourceManager.GetObject("text5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_1 {
            get {
                object obj = ResourceManager.GetObject("Untitled-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_2 {
            get {
                object obj = ResourceManager.GetObject("Untitled-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_3 {
            get {
                object obj = ResourceManager.GetObject("Untitled-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_4 {
            get {
                object obj = ResourceManager.GetObject("Untitled-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
