//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEO_FingerScan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEO_FingerScan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap fingerPrint_BG {
            get {
                object obj = ResourceManager.GetObject("fingerPrint-BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap l0 {
            get {
                object obj = ResourceManager.GetObject("l0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_no_finger {
            get {
                object obj = ResourceManager.GetObject("main-no-finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_no_finger1 {
            get {
                object obj = ResourceManager.GetObject("main-no-finger1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r1_c1 {
            get {
                object obj = ResourceManager.GetObject("main0_r1_c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r1_c1_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r1_c1_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r1_c2 {
            get {
                object obj = ResourceManager.GetObject("main0_r1_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r1_c2_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r1_c2_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c2 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c2_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c2_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c2_f21 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c2_f21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c21 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c4 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c4_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c4_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c5 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c5_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c5_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c51 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c6 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r2_c6_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r2_c6_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r3_c2 {
            get {
                object obj = ResourceManager.GetObject("main0_r3_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r3_c2_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r3_c2_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c2 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c2_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c2_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c3 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c3_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c3_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c7 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r4_c7_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r4_c7_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r5_c3 {
            get {
                object obj = ResourceManager.GetObject("main0_r5_c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main0_r5_c3_f2 {
            get {
                object obj = ResourceManager.GetObject("main0_r5_c3_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap r0 {
            get {
                object obj = ResourceManager.GetObject("r0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r4_c4 {
            get {
                object obj = ResourceManager.GetObject("setting_r4_c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r4_c4_f2 {
            get {
                object obj = ResourceManager.GetObject("setting_r4_c4_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r4_c6 {
            get {
                object obj = ResourceManager.GetObject("setting_r4_c6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r4_c6_f2 {
            get {
                object obj = ResourceManager.GetObject("setting_r4_c6_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r6_c2 {
            get {
                object obj = ResourceManager.GetObject("setting_r6_c2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r6_c2_f2 {
            get {
                object obj = ResourceManager.GetObject("setting_r6_c2_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r6_c3 {
            get {
                object obj = ResourceManager.GetObject("setting_r6_c3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r6_c3_f2 {
            get {
                object obj = ResourceManager.GetObject("setting_r6_c3_f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setting_r6_c3_f21 {
            get {
                object obj = ResourceManager.GetObject("setting_r6_c3_f21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spacer {
            get {
                object obj = ResourceManager.GetObject("spacer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
